name: CI workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: python:3.9-slim
    services:
      postgres:
        image: postgres:latest
        env:
          # Replace <user>, <password>, and <db> with your own PostgreSQL information
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt' )}}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip  
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
      - name: Upload coverage report
        uses: actions/upload-artifact@v2 
        with:
          name: coverage-report 
          path: coverage.xml